[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install"

[deploy]
startCommand = "node /app/server/index.js"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
